"""
This type stub file was generated by pyright.
"""

class SATestSuiteWarning(Warning):
    """warning for a condition detected during tests that is non-fatal

    Currently outside of SAWarning so that we can work around tools like
    Alembic doing the wrong thing with warnings.

    """
    ...


def warn_test_suite(message): # -> None:
    ...

def setup_filters(): # -> None:
    """Set global warning behavior for the test suite."""
    ...

def assert_warnings(fn, warning_msgs, regex=...):
    """Assert that each of the given warnings are emitted by fn.

    Deprecated.  Please use assertions.expect_warnings().

    """
    ...

