# redis_migration_mcp.py
import asyncio
from pathlib import Path
from typing import Dict, List, Optional
import ast
import json
from mcp.server import Server
from mcp.types import Tool, TextContent, Resource
import aioredis
import asyncpg

server = Server("system-rebellion-redis-migrator")

class CodeAnalyzer:
    """Analyzes your System Rebellion code for DB operations"""
    
    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.agents = {}
        
    async def scan_for_agents(self):
        """Finds all agent files and their DB operations"""
        for py_file in self.project_root.rglob("*.py"):
            content = py_file.read_text()
            if "PostgreSQLConnection" in content or "self.db" in content:
                self.agents[py_file.name] = {
                    "path": py_file,
                    "operations": self._extract_db_operations(content)
                }
    
    def _extract_db_operations(self, content: str) -> List[Dict]:
        """Extracts DB operations from Python code"""
        operations = []
        tree = ast.parse(content)
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if hasattr(node.func, 'attr'):
                    if node.func.attr in ['execute', 'fetch', 'fetchrow', 'fetchval']:
                        operations.append({
                            "type": node.func.attr,
                            "line": node.lineno,
                            "query": self._extract_query(node)
                        })
        return operations

@server.tool()
async def analyze_agent_db_usage(agent_name: str) -> Dict:
    """Analyzes how a specific agent uses the database"""
    analyzer = CodeAnalyzer(Path("."))
    await analyzer.scan_for_agents()
    
    agent_patterns = {
        "sir_hawkington": {
            "redis_structure": "sorted_sets",
            "reason": "Needs ordered system metrics with timestamps"
        },
        "meth_snail": {
            "redis_structure": "streams",
            "reason": "High-speed optimization events in sequence"
        },
        "hamsters": {
            "redis_structure": "hash_sets",
            "reason": "Key-value storage for duct-tape solutions"
        }
    }
    
    return {
        "agent": agent_name,
        "current_operations": analyzer.agents.get(f"{agent_name}.py", {}),
        "recommended_redis": agent_patterns.get(agent_name, {}),
        "migration_complexity": "moderate"
    }

@server.tool()
async def generate_redis_migration(
    agent_file: str,
    postgres_operation: str
) -> str:
    """Generates Redis equivalent for PostgreSQL operation"""
    
    # Parse the Postgres operation
    if "INSERT INTO" in postgres_operation:
        return generate_redis_insert(postgres_operation)
    elif "SELECT" in postgres_operation:
        return generate_redis_select(postgres_operation)
    elif "UPDATE" in postgres_operation:
        return generate_redis_update(postgres_operation)
    
def generate_redis_insert(pg_query: str) -> str:
    """Converts PostgreSQL INSERT to Redis operation"""
    # Extract table and values
    # Example: INSERT INTO metrics (agent_id, cpu, memory) VALUES ($1, $2, $3)
    
    template = '''
# Redis equivalent using hash sets
await redis.hset(
    f"agent:{agent_id}:metrics",
    mapping={
        "cpu": cpu_value,
        "memory": memory_value,
        "timestamp": int(time.time())
    }
)

# Also add to sorted set for time-series queries
await redis.zadd(
    f"metrics:timeline",
    {f"{agent_id}:{timestamp}": timestamp}
)
'''
    return template

@server.tool()
async def create_migration_script(
    target_directory: str = "./migrations"
) -> Dict:
    """Creates a full migration script for all agents"""
    
    migration_template = '''#!/usr/bin/env python3
"""
System Rebellion PostgreSQL -> Redis Migration
Generated by MCP Server
Personality-aware migration maintaining agent characteristics
"""

import asyncio
import asyncpg
import aioredis
from datetime import datetime

class SystemRebellionMigration:
    def __init__(self):
        self.postgres = None
        self.redis = None
        
    async def connect(self):
        self.postgres = await asyncpg.connect('postgresql://...')
        self.redis = await aioredis.create_redis_pool('redis://...')
        
    async def migrate_sir_hawkington(self):
        """Migrates Sir Hawkington's refined metrics"""
        print("🎩 Migrating Sir Hawkington's distinguished data...")
        
        # Fetch historical data
        rows = await self.postgres.fetch(
            "SELECT * FROM metrics WHERE agent_id = 'sir_hawkington'"
        )
        
        # Store in Redis sorted sets (maintaining order, as a gentleman would)
        for row in rows:
            await self.redis.zadd(
                'sir_hawkington:metrics',
                {json.dumps(dict(row)): row['timestamp']}
            )
            
    async def migrate_meth_snail(self):
        """Migrates Meth Snail's chaotic optimization logs"""
        print("🐌💨 MIGRATING AT MAXIMUM SPEED...")
        
        # Use Redis Streams for high-speed event tracking
        rows = await self.postgres.fetch(
            "SELECT * FROM optimizations WHERE agent_id = 'meth_snail'"
        )
        
        for row in rows:
            await self.redis.xadd(
                'meth_snail:optimizations',
                {'data': json.dumps(dict(row))}
            )
            
    async def migrate_hamsters(self):
        """Migrates Steve, Bob, and Carl's duct-tape solutions"""
        print("🐹🍺 Hold my beer, migrating data...")
        
        # Simple hash sets for hamster solutions
        for hamster in ['steve', 'bob', 'carl']:
            rows = await self.postgres.fetch(
                f"SELECT * FROM solutions WHERE agent_id = '{hamster}'"
            )
            
            for row in rows:
                await self.redis.hset(
                    f'{hamster}:solutions',
                    f"solution_{row['id']}",
                    json.dumps(dict(row))
                )

if __name__ == "__main__":
    migration = SystemRebellionMigration()
    asyncio.run(migration.run())
'''
    
    # Write the migration script
    Path(target_directory).mkdir(exist_ok=True)
    migration_file = Path(target_directory) / f"migrate_redis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py"
    migration_file.write_text(migration_template)
    
    return {
        "status": "success",
        "file": str(migration_file),
        "message": "Migration script created with personality preservation!"
    }

@server.tool()
async def test_redis_patterns(pattern_type: str, sample_data: Dict) -> Dict:
    """Tests Redis patterns with sample data"""
    test_results = {}
    
    # Connect to test Redis
    redis = await aioredis.create_redis_pool('redis://localhost:6379/15')  # Test DB
    
    try:
        if pattern_type == "sorted_set":
            # Test Sir Hawkington's pattern
            await redis.zadd('test:metrics', {json.dumps(sample_data): time.time()})
            result = await redis.zrange('test:metrics', 0, -1, withscores=True)
            test_results['sorted_set'] = {"success": True, "data": result}
            
        elif pattern_type == "stream":
            # Test Meth Snail's pattern  
            msg_id = await redis.xadd('test:stream', sample_data)
            test_results['stream'] = {"success": True, "message_id": msg_id}
            
        elif pattern_type == "hash":
            # Test Hamster pattern
            await redis.hset('test:hamster', mapping=sample_data)
            result = await redis.hgetall('test:hamster')
            test_results['hash'] = {"success": True, "data": result}
            
    finally:
        redis.close()
        await redis.wait_closed()
        
    return test_results

@server.resource()
async def get_migration_status() -> Resource:
    """Returns current migration status"""
    return Resource(
        uri="redis://migration/status",
        name="Migration Status",
        content=TextContent(
            text=json.dumps({
                "agents_analyzed": ["sir_hawkington", "meth_snail", "steve", "bob", "carl"],
                "redis_patterns_identified": {
                    "sorted_sets": "Sir Hawkington's metrics",
                    "streams": "Meth Snail's optimizations",
                    "hash_sets": "Hamster solutions",
                    "pub_sub": "Inter-agent communication"
                },
                "ready_to_migrate": True
            }, indent=2)
        )
    )

# Run the server
if __name__ == "__main__":
    import sys
    from mcp.server.stdio import stdio_server
    
    asyncio.run(stdio_server(server))