# Exported from Render on 2025-05-20T04:04:36Z
databases:
- name: System Rebellion HQ
  databaseName: system_rebellion_hq
  user: system_rebellion_hq_user
  plan: free
  region: ohio
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: System Rebellion HQ
  runtime: python
  repo: https://github.com/carissab96/system_rebellion
  branch: Main
  plan: free
  region: ohio
  buildCommand: pip install -r backend/requirements.txt && python -m alembic -c backend/alembic.ini
    upgrade head && npm install --prefix frontend && npm run build --prefix frontend
  startCommand: python backend/app/optimization/system_permissions.py && python backend/setup_permissions.py
    && python backend/app/core/init_db.py && uvicorn backend/main:app --host 0.0.0.0
    --port $PORT & npm run start --prefix frontend
  healthCheckPath: /api/health-check
  autoDeployTrigger: commit
version: "1"
