"""
This type stub file was generated by pyright.
"""

"""defines generic type conversion functions, as used in bind and result
processors.

They all share one common characteristic: None is passed through unchanged.

"""
def str_to_datetime_processor_factory(regexp, type_): # -> Callable[..., Any | None]:
    ...

def py_fallback(): # -> dict[str, Any]:
    ...

def to_unicode_processor_factory(encoding, errors=...):
    ...

def to_conditional_unicode_processor_factory(encoding, errors=...):
    ...

def to_decimal_processor_factory(target_class, scale):
    ...

