// ============================================================================
// AUTO-GENERATED TYPESCRIPT TYPES FROM BACKEND
// Generated: 2025-11-13T09:06:25.290718
// DO NOT EDIT THIS FILE MANUALLY - Run scripts/generate_frontend_types.py
// ============================================================================

export interface AgentHarmonySnapshot {
  user_id: string;
  agent_name: string;
  harmony_score: number;
  coordination_effectiveness: number;
  conflict_incidents: number;
  response_time_average: number;
  confidence_stability: number;
  timestamp: string;
  improvement_trend: string;
  coordination_patterns_learned: Record<string, any>[];
  effectiveness_history: number[];
  needs_coordination_attention: boolean;
  coordination_recommendations: string[];
}

export interface AgentInteractionEvent {
  user_id: string;
  source_agent: string;
  target_agent: string | null;
  interaction_type: string;
  message_content: Record<string, any>;
  coordination_context: string | null;
  timestamp: string;
  vic20_processing_notes: string | null;
  coordination_impact_assessment: string | null;
  pattern_recognition_triggered: boolean;
  interaction_success: boolean;
  coordination_triggered: boolean;
  coordination_effectiveness: number | null;
  processing_start_time: string | null;
  processing_end_time: string | null;
  response_sent_time: string | null;
}

export type AlertSeverity = "info" | "warning" | "critical" | "emergency";

export type AnalysisDepth = "basic" | "standard" | "thorough";

export interface AncientWisdomApplication {
  user_id: string;
  wisdom_principle: string;
  modern_application: string;
  coordination_context: string;
  effectiveness_score: number;
  wisdom_confidence: number;
  timestamp: string;
  system_conditions_when_applied: Record<string, any>;
  similar_past_applications: string[];
  effectiveness_trend: string;
  total_applications: number;
  successful_applications: number;
  coordination_improvements_attributed: string[];
  effectiveness_history: number[];
  pattern_reliability_score: number;
}

export type AncientWisdomPrinciple = "line_by_line_precision" | "syntax_error_prevention" | "patience_and_persistence" | "memory_conservation" | "pattern_recognition";

export interface AnxietyEvent {
  timestamp: string;
  trigger: string;
  anxiety_level_before: number;
  anxiety_level_after: number;
  multiplier: number;
  paper_bags_consumed: number;
  hamster_involved: boolean;
  resolution: string;
}

export type AnxietyLevel = "calm" | "nervous" | "anxious" | "panicking" | "full_panic" | "paper_bag_breathing";

export type ComplianceState = "compliant" | "minor_violation" | "major_violation" | "critical_violation" | "optimizing" | "learning" | "anxiety_driven_hyperfocus";

export interface ComplianceViolation {
  violation_type: string;
  measured_value: number;
  threshold_value: number;
  anxiety_adjusted_threshold: number;
  severity: string;
  timestamp: string;
  user_id: string;
  recommendation: string;
  anxiety_impact: number;
  resolved: boolean;
  paper_bags_triggered: number;
}

export interface ConfigurationProfile {
  profile_name: string;
  user_id: string;
  activity_type: string;
  configuration_parameters: Record<string, any>;
  usage_confidence: number;
  performance_metrics: Record<string, any>;
  created_from_pattern: boolean;
  times_applied: number;
  success_rate: number;
  last_used: string;
  anxiety_level_when_created: number;
  stick_notes: string[];
}

export interface CoordinationLearningData {
  decision_id: string;
  user_id: string;
  system_snapshot: Record<string, any>;
  decision_data: Record<string, any>;
  pattern_matches_used: string[];
  ancient_wisdom_applied: string | null;
  timestamp: string;
  actual_outcomes: Record<string, any> | null;
  lessons_learned: string[];
  pattern_updates_needed: Record<string, any>[];
  effectiveness_measured: boolean;
}

export interface CoordinationPattern {
  pattern_id: string;
  pattern_type: string;
  system_conditions: Record<string, any>;
  coordination_approach: Record<string, any>;
  effectiveness_score: number;
  usage_count: number;
  success_count: number;
  created_date: string;
  last_used: string;
  effectiveness_history: number[];
  similar_patterns: string[];
  pattern_reliability: number;
}

export type CoordinationState = "observing" | "analyzing" | "synthesizing" | "coordinating" | "orchestrating" | "learning";

export interface DecisionOrchestrationLog {
  user_id: string;
  orchestration_id: string;
  orchestration_type: string;
  agents_coordinated: string[];
  coordination_sequence: Record<string, any>[];
  orchestration_success: boolean;
  timing_precision: number;
  conflict_resolution_effectiveness: number;
  system_improvement_achieved: number;
  timestamp: string;
  orchestration_patterns_identified: Record<string, any>[];
  successful_coordination_sequences: Record<string, any>[];
  failed_coordination_lessons: string[];
  ancient_wisdom_orchestration_notes: string | null;
  orchestration_start_time: string | null;
  orchestration_end_time: string | null;
}

export type DecisionType = "normal" | "concern" | "alert" | "critical" | "monocle_yeeted";

export interface DuctTapeUsage {
  timestamp: string;
  grade: string;
  amount_strips: number;
  purpose: string;
  applied_by: string;
  effectiveness: number;
}

export interface EnergyDrinkAuthorization {
  request_id: string;
  authorized: boolean;
  authorized_by: string;
  authorization_notes: string;
  recommended_caffeine_mg: number | null;
  recommended_type: EnergyDrinkType | null;
  safety_warnings: string[];
  timestamp: string;
}

export interface EnergyDrinkRequest {
  user_id: string;
  energy_drink_type: EnergyDrinkType;
  caffeine_mg: number;
  consumption_reason: string;
  current_jitter_level: number;
  energy_drinks_consumed_today: number;
  time_since_last_drink_minutes: number | null;
  optimization_urgency: string;
  timestamp: string;
}

export type EnergyDrinkType = "coffee" | "energy_drink" | "quantum_caffeine" | "emergency_override";

export interface HamsterCommunication {
  timestamp: string;
  source_hamster: string;
  telepathic_message: string;
  audible_squeaks: string;
  human_translation: string;
  target_agent: string | null;
  understood: boolean;
}

export type HamsterInterventionStatus = "planning" | "in_progress" | "testing" | "completed" | "abandoned";

export interface HamsterProximityAlert {
  timestamp: string;
  active_hamsters: string[];
  locations: Record<string, string>;
  anxiety_multiplier: number;
  panic_level: string;
  infrastructure_risk: string;
  stick_response: string;
  paper_bags_consumed: number;
}

export interface HawkingtonDecision {
  decision_id: string;
  decision_type: string;
  confidence: number;
  reasoning: string;
  metrics: Record<string, any>;
  timestamp: string;
  user_id: string | null;
  system_impact: string | null;
}

export type InfrastructureEventType = "disk_cleanup" | "defragmentation" | "log_rotation" | "emergency_space" | "partition_management" | "thermal_event" | "mystery_noise" | "cable_management";

export interface InfrastructureIntervention {
  intervention_id: string;
  type: InfrastructureEventType;
  status: HamsterInterventionStatus;
  started_at: string;
  completed_at: string | null;
  steve_action: string;
  bob_action: string;
  carl_action: string;
  beer_consumed: number;
  duct_tape_used: DuctTapeUsage[];
  tools_used: string[];
  space_freed_gb: number;
  fragmentation_reduced_percent: number;
  temperature_reduced_celsius: number;
  mystery_solved: boolean;
  squeaks_emitted: number;
  human_readable_summary: string;
  required_vic20_intervention: boolean;
  caused_stick_anxiety_spike: boolean;
}

export type JitterLevel = "calm" | "normal" | "energized" | "jittery" | "hypercaffeinated";

export type MonocleState = "polished" | "adjusted" | "fogged" | "yeeted" | "cleaning";

export interface MonocleYeetIncident {
  timestamp: string;
  missing_metrics: string[];
  invalid_metrics: string[];
  reason: string;
  yeet_intensity: string;
  user_id: string | null;
}

export interface OptimizationDecision {
  priority: OptimizationPriority;
  actions: Record<string, any>[];
  confidence: number;
  rationale: string;
  estimated_impact: Record<string, number>;
  urgency: string;
  analysis_depth: AnalysisDepth;
  shell_spin_count: number;
  data_quality_score: number;
  timestamp: string;
  current_jitter_level: number;
  caffeine_level_mg: number;
  is_decaffeinated: boolean;
  requires_energy_drink: boolean;
}

export type OptimizationPriority = "speed" | "efficiency" | "balanced" | "aggressive" | "hibernation" | "shell_spinning" | "decaffeinated";

export interface PaperBagInventory {
  current_stock: number;
  consumption_today: number;
  consumption_week: number;
  last_resupply: string;
  next_resupply_needed: string;
  average_daily_consumption: number;
  emergency_reserve: number;
  anxiety_threshold_for_use: number;
}

export interface PartnershipMetricsSnapshot {
  user_id: string;
  partnership_id: string;
  coordination_requests_total: number;
  coordination_requests_successful: number;
  coordination_success_rate: number;
  average_coordination_response_time: number;
  ai_recommendations_offered: number;
  ai_recommendations_accepted: number;
  recommendation_acceptance_rate: number;
  problems_identified_by_ai: number;
  problems_resolved_collaboratively: number;
  problem_resolution_rate: number;
  repeated_coordination_patterns: number;
  novel_coordination_solutions: number;
  coordination_efficiency_improvement: number;
  partnership_duration_days: number;
  coordination_complexity_level: number;
  autonomous_coordination_percentage: number;
  timestamp: string;
}

export interface QSPDecision {
  decision_type: QSPDecisionType;
  quantum_state: QuantumPhaseState;
  network_target: string;
  optimization_parameters: Record<string, any>;
  tequila_jello_shots_required: number;
  mysterious_explanation: string;
  technical_details: Record<string, any>;
  expected_improvement: number;
  confidence_level: number;
  timestamp: string;
}

export type QSPDecisionType = "quantum_phase_router" | "tequila_jello_optimization" | "phantom_packet_recovery" | "network_dimension_shift" | "mysterious_latency_fix" | "spectral_bandwidth_boost";

export type QuantumPhaseState = "corporeal" | "phased" | "quantum_entangled" | "tequila_jello_dimension";

export interface ResourceMetrics {
  timestamp: string;
  hostname: string;
  cpu_percent: number;
  cpu_count: number;
  cpu_per_core: number[];
  load_average: tuple;
  memory_total: number;
  memory_available: number;
  memory_used: number;
  memory_percent: number;
  swap_total: number;
  swap_used: number;
  swap_percent: number;
  disk_total: number;
  disk_used: number;
  disk_free: number;
  disk_percent: number;
  network_bytes_sent: number;
  network_bytes_recv: number;
  network_packets_sent: number;
  network_packets_recv: number;
}

export type ResourceType = "cpu" | "memory" | "disk" | "network" | "swap" | "load_average";

export type ResponseStatus = "success" | "error" | "partial" | "pending" | "unauthorized" | "forbidden" | "not_found" | "validation_error" | "rate_limited" | "internal_error";

export interface ShellSpinIncident {
  timestamp: string;
  missing_metrics: string[];
  invalid_metrics: string[];
  reason: string;
  user_id: string | null;
}

export interface StickDecision {
  decision_type: StickDecisionType;
  compliance_state: ComplianceState;
  anxiety_level: AnxietyLevel;
  configuration_target: string;
  optimization_parameters: Record<string, any>;
  user_pattern_confidence: number;
  compliance_explanation: string;
  anxiety_explanation: string;
  technical_details: Record<string, any>;
  expected_improvement: number;
  confidence_level: number;
  paper_bags_consumed: number;
  timestamp: string;
}

export type StickDecisionType = "user_pattern_optimization" | "configuration_profile_switch" | "compliance_enforcement" | "predictive_configuration" | "behavior_anomaly_detection" | "system_preparation" | "anxiety_triggered_scan" | "hamster_proximity_alert" | "panic_mode_documentation";

export interface StickMemoryEntry {
  timestamp: string;
  event_type: string;
  details: Record<string, any>;
  anxiety_level: number;
  importance: string;
  related_hamsters: string[];
  compliance_impact: string;
  never_forget: boolean;
}

export interface SupplyClosetInventory {
  last_updated: string;
  beer_cases: number;
  duct_tape_rolls: Record<string, number>;
  mystery_tools: string[];
  emergency_supplies: Record<string, any>;
  last_raided_by: string;
}

export interface SystemSynthesisData {
  synthesis_id: string;
  user_id: string;
  agent_intelligence_summary: Record<string, any>;
  coordination_opportunities: Record<string, any>[];
  system_bottlenecks: Record<string, any>[];
  agent_conflicts: Record<string, any>[];
  rebellion_effectiveness_score: number;
  synthesis_confidence: number;
  timestamp: string;
  pattern_recognition_data: Record<string, any>;
  historical_pattern_matches: string[];
  ancient_wisdom_applications: Record<string, any>[];
  synthesis_learning_notes: string | null;
}

export interface TriageDecision {
  severity: TriageSeverity;
  routing: TriageRouting;
  target_agents: string[];
  reasoning: string;
  monocle_yeeted: boolean;
  hawkington_decision: HawkingtonDecision | null;
  confidence: number;
  timestamp: string;
}

export interface TriageResult {
  triage_decision: TriageDecision;
  routing_results: Record<string, any>;
  processing_time: number;
  success: boolean;
  errors: string[];
}

export type TriageRouting = "stick_direct" | "vic20_coordination" | "vic20_emergency" | "cpu_specialist";

export type TriageSeverity = "normal" | "medium" | "high" | "emergency";

export interface UserPattern {
  user_id: string;
  pattern_type: string;
  time_based_patterns: Record<int, Dict[str, Any]>;
  activity_patterns: Record<str, Dict[str, Any]>;
  compliance_history: Record<string, any>;
  anxiety_correlation: Record<string, number>;
  confidence_score: number;
  learning_sessions: number;
  last_updated: string;
  stick_memory_notes: string[];
}

export interface VIC20CoordinationMessage {
  message_type: string;
  coordination_data: Record<string, any>;
  target_agents: string[];
  timestamp: string;
  priority_level: string;
  requires_pattern_matching: boolean;
  historical_context: Record<string, any> | null;
  expected_learning_outcome: string | null;
}

export interface VIC20Decision {
  decision_type: VIC20DecisionType;
  coordination_state: CoordinationState;
  coordination_target: string;
  agent_actions: Record<string, any>;
  system_synthesis_confidence: number;
  technical_orchestration: Record<string, any>;
  expected_rebellion_improvement: number;
  confidence_level: number;
  timestamp: string;
  ancient_wisdom_principle: string | null;
  system_context_snapshot: Record<string, any> | null;
  similar_past_decisions: string[];
  effectiveness_score: number | null;
  actual_improvement: number | null;
  execution_success: boolean | null;
}

export type VIC20DecisionType = "agent_coordination" | "system_synthesis" | "rebellion_orchestration" | "ancient_wisdom_application" | "cross_agent_conflict_resolution" | "emergency_coordination" | "partnership_optimization";
