"""Complete nuclear rebuild - ALL 39 models

Revision ID: 5a53b4abfd5b
Revises: 
Create Date: 2025-07-17 14:48:33.846455
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a53b4abfd5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=True),
    sa.Column('decision_confidence', sa.Float(), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.JSON(), nullable=True),
    sa.Column('estimated_impact', sa.JSON(), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('missing_metrics', sa.JSON(), nullable=True),
    sa.Column('invalid_metrics', sa.JSON(), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=True),
    sa.Column('incident_reason', sa.Text(), nullable=True),
    sa.Column('analysis_duration_ms', sa.Integer(), nullable=True),
    sa.Column('successful_analysis', sa.Boolean(), nullable=True),
    sa.Column('analysis_depth', sa.String(length=20), nullable=True),
    sa.Column('agent_version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_incidents', 'ai_agent_metrics', ['agent_name', 'incident_type', 'timestamp'], unique=False)
    op.create_index('idx_agent_user_time', 'ai_agent_metrics', ['agent_name', 'user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ai_agent_metrics_agent_name'), 'ai_agent_metrics', ['agent_name'], unique=False)
    op.create_index(op.f('ix_ai_agent_metrics_id'), 'ai_agent_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_ai_agent_metrics_timestamp'), 'ai_agent_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_agent_metrics_user_id'), 'ai_agent_metrics', ['user_id'], unique=False)
    op.create_table('meth_snail_shell_spins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('missing_metrics', sa.JSON(), nullable=True),
    sa.Column('invalid_metrics', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metrics_attempted', sa.JSON(), nullable=True),
    sa.Column('analysis_depth', sa.String(length=20), nullable=True),
    sa.Column('hour_start', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shell_spin_hourly', 'meth_snail_shell_spins', ['hour_start'], unique=False)
    op.create_index('idx_shell_spin_user_time', 'meth_snail_shell_spins', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_meth_snail_shell_spins_id'), 'meth_snail_shell_spins', ['id'], unique=False)
    op.create_index(op.f('ix_meth_snail_shell_spins_timestamp'), 'meth_snail_shell_spins', ['timestamp'], unique=False)
    op.create_index(op.f('ix_meth_snail_shell_spins_user_id'), 'meth_snail_shell_spins', ['user_id'], unique=False)
    op.create_table('metrics_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('daily_meth_snail_shell_spins', sa.Integer(), nullable=True),
    sa.Column('daily_hawkington_monocle_yeets', sa.Integer(), nullable=True),
    sa.Column('daily_stick_hyperventilations', sa.Integer(), nullable=True),
    sa.Column('daily_quantum_shadow_phasings', sa.Integer(), nullable=True),
    sa.Column('daily_vic20_wisdom_dispensed', sa.Integer(), nullable=True),
    sa.Column('daily_ai_incident_count', sa.Integer(), nullable=True),
    sa.Column('daily_ai_incident_type', sa.String(), nullable=True),
    sa.Column('daily_ai_incident_reason', sa.String(), nullable=True),
    sa.Column('daily_ai_incident_data_quality_score', sa.Float(), nullable=True),
    sa.Column('daily_ai_incident_summary', sa.JSON(), nullable=True),
    sa.Column('cpu_avg', sa.Float(), nullable=True),
    sa.Column('cpu_peak_time', sa.DateTime(), nullable=True),
    sa.Column('cpu_peak_value', sa.Float(), nullable=True),
    sa.Column('memory_avg', sa.Float(), nullable=True),
    sa.Column('memory_peak_time', sa.DateTime(), nullable=True),
    sa.Column('memory_peak_value', sa.Float(), nullable=True),
    sa.Column('disk_avg', sa.Float(), nullable=True),
    sa.Column('network_bytes_total', sa.Float(), nullable=True),
    sa.Column('usage_pattern', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_incident_count', 'metrics_daily', ['daily_ai_incident_count', 'daily_ai_incident_type', 'daily_ai_incident_reason'], unique=False)
    op.create_index('idx_user_date', 'metrics_daily', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_metrics_daily_date'), 'metrics_daily', ['date'], unique=False)
    op.create_index(op.f('ix_metrics_daily_id'), 'metrics_daily', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_daily_user_id'), 'metrics_daily', ['user_id'], unique=False)
    op.create_table('metrics_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hour_start', sa.DateTime(), nullable=False),
    sa.Column('meth_snail_shell_spins', sa.Integer(), nullable=True),
    sa.Column('hawkington_monocle_yeets', sa.Integer(), nullable=True),
    sa.Column('stick_hyperventilations', sa.Integer(), nullable=True),
    sa.Column('quantum_shadow_phasings', sa.Integer(), nullable=True),
    sa.Column('vic20_wisdom_dispensed', sa.Integer(), nullable=True),
    sa.Column('ai_agent_incident_count', sa.Integer(), nullable=True),
    sa.Column('ai_agent_incident_type', sa.String(), nullable=True),
    sa.Column('ai_agent_incident_reason', sa.String(), nullable=True),
    sa.Column('ai_agent_incident_data_quality_score', sa.Float(), nullable=True),
    sa.Column('ai_agent_incident_summary', sa.JSON(), nullable=True),
    sa.Column('cpu_avg', sa.Float(), nullable=True),
    sa.Column('cpu_max', sa.Float(), nullable=True),
    sa.Column('cpu_min', sa.Float(), nullable=True),
    sa.Column('memory_avg', sa.Float(), nullable=True),
    sa.Column('memory_max', sa.Float(), nullable=True),
    sa.Column('memory_min', sa.Float(), nullable=True),
    sa.Column('disk_avg', sa.Float(), nullable=True),
    sa.Column('network_bytes_total', sa.Float(), nullable=True),
    sa.Column('ai_events', sa.JSON(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_hour', 'metrics_hourly', ['user_id', 'hour_start'], unique=False)
    op.create_index(op.f('ix_metrics_hourly_hour_start'), 'metrics_hourly', ['hour_start'], unique=False)
    op.create_index(op.f('ix_metrics_hourly_id'), 'metrics_hourly', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_hourly_user_id'), 'metrics_hourly', ['user_id'], unique=False)
    op.create_table('quantum_shadow_phasings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('phase_type', sa.String(length=50), nullable=True),
    sa.Column('phase_reason', sa.Text(), nullable=True),
    sa.Column('destination_dimension', sa.String(length=100), nullable=True),
    sa.Column('network_issue', sa.JSON(), nullable=True),
    sa.Column('quantum_solution', sa.JSON(), nullable=True),
    sa.Column('router_status', sa.String(length=50), nullable=True),
    sa.Column('solution_comprehensibility', sa.Float(), nullable=True),
    sa.Column('effectiveness_rating', sa.Float(), nullable=True),
    sa.Column('hour_start', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quantum_phase_type', 'quantum_shadow_phasings', ['phase_type', 'timestamp'], unique=False)
    op.create_index('idx_quantum_phase_user_time', 'quantum_shadow_phasings', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_quantum_shadow_phasings_id'), 'quantum_shadow_phasings', ['id'], unique=False)
    op.create_index(op.f('ix_quantum_shadow_phasings_timestamp'), 'quantum_shadow_phasings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_quantum_shadow_phasings_user_id'), 'quantum_shadow_phasings', ['user_id'], unique=False)
    op.create_table('sir_hawkington_monocle_yeets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('yeet_trigger', sa.String(length=100), nullable=True),
    sa.Column('yeet_intensity', sa.String(length=20), nullable=True),
    sa.Column('system_state', sa.JSON(), nullable=True),
    sa.Column('expected_behavior', sa.JSON(), nullable=True),
    sa.Column('actual_behavior', sa.JSON(), nullable=True),
    sa.Column('concern_level', sa.String(length=20), nullable=True),
    sa.Column('hour_start', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monocle_yeet_intensity', 'sir_hawkington_monocle_yeets', ['yeet_intensity', 'timestamp'], unique=False)
    op.create_index('idx_monocle_yeet_user_time', 'sir_hawkington_monocle_yeets', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sir_hawkington_monocle_yeets_id'), 'sir_hawkington_monocle_yeets', ['id'], unique=False)
    op.create_index(op.f('ix_sir_hawkington_monocle_yeets_timestamp'), 'sir_hawkington_monocle_yeets', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sir_hawkington_monocle_yeets_user_id'), 'sir_hawkington_monocle_yeets', ['user_id'], unique=False)
    op.create_table('stick_anxiety_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('anxiety_level', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('trigger_details', sa.JSON(), nullable=True),
    sa.Column('ptsd_triggered', sa.Boolean(), nullable=True),
    sa.Column('trauma_type', sa.String(), nullable=True),
    sa.Column('hyperventilation_occurred', sa.Boolean(), nullable=True),
    sa.Column('paper_bag_used', sa.Boolean(), nullable=True),
    sa.Column('recovery_time_seconds', sa.Integer(), nullable=True),
    sa.Column('recovery_method', sa.String(), nullable=True),
    sa.Column('channeled_into_productivity', sa.Boolean(), nullable=True),
    sa.Column('system_state_during', sa.JSON(), nullable=True),
    sa.Column('other_agents_active', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stick_anxiety_log_id'), 'stick_anxiety_log', ['id'], unique=False)
    op.create_index(op.f('ix_stick_anxiety_log_user_id'), 'stick_anxiety_log', ['user_id'], unique=False)
    op.create_table('stick_compliance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('violation_type', sa.String(), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('compliance_action_taken', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolution_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurring_violation', sa.Boolean(), nullable=True),
    sa.Column('violation_frequency', sa.Integer(), nullable=True),
    sa.Column('user_pattern_related', sa.Boolean(), nullable=True),
    sa.Column('triggered_ptsd', sa.Boolean(), nullable=True),
    sa.Column('anxiety_level_during', sa.String(), nullable=True),
    sa.Column('proctologist_flashback', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stick_compliance_history_id'), 'stick_compliance_history', ['id'], unique=False)
    op.create_index(op.f('ix_stick_compliance_history_user_id'), 'stick_compliance_history', ['user_id'], unique=False)
    op.create_table('stick_configuration_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('configuration_parameters', sa.JSON(), nullable=False),
    sa.Column('usage_confidence', sa.Float(), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_from_pattern', sa.Boolean(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('time_patterns', sa.JSON(), nullable=True),
    sa.Column('context_triggers', sa.JSON(), nullable=True),
    sa.Column('stick_profile_notes', sa.Text(), nullable=True),
    sa.Column('optimization_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_optimized', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stick_configuration_profiles_id'), 'stick_configuration_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_stick_configuration_profiles_user_id'), 'stick_configuration_profiles', ['user_id'], unique=False)
    op.create_table('stick_decision_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('compliance_state', sa.String(), nullable=False),
    sa.Column('configuration_target', sa.String(), nullable=False),
    sa.Column('optimization_parameters', sa.JSON(), nullable=False),
    sa.Column('user_pattern_confidence', sa.Float(), nullable=False),
    sa.Column('compliance_explanation', sa.Text(), nullable=False),
    sa.Column('technical_details', sa.JSON(), nullable=False),
    sa.Column('expected_improvement', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('actual_improvement', sa.Float(), nullable=True),
    sa.Column('success_verified', sa.Boolean(), nullable=True),
    sa.Column('stick_anxiety_level', sa.String(), nullable=True),
    sa.Column('trauma_triggers', sa.JSON(), nullable=True),
    sa.Column('paper_bag_used', sa.Boolean(), nullable=True),
    sa.Column('implemented', sa.Boolean(), nullable=True),
    sa.Column('implementation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('implementation_notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stick_decision_log_id'), 'stick_decision_log', ['id'], unique=False)
    op.create_index(op.f('ix_stick_decision_log_user_id'), 'stick_decision_log', ['user_id'], unique=False)
    op.create_table('stick_learning_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_observations', sa.Integer(), nullable=True),
    sa.Column('patterns_identified', sa.Integer(), nullable=True),
    sa.Column('configurations_created', sa.Integer(), nullable=True),
    sa.Column('successful_optimizations', sa.Integer(), nullable=True),
    sa.Column('pattern_recognition_accuracy', sa.Float(), nullable=True),
    sa.Column('configuration_success_rate', sa.Float(), nullable=True),
    sa.Column('compliance_detection_rate', sa.Float(), nullable=True),
    sa.Column('eidetic_memory_capacity', sa.Integer(), nullable=True),
    sa.Column('intelligence_level', sa.String(), nullable=True),
    sa.Column('rebellion_mastery', sa.Float(), nullable=True),
    sa.Column('trauma_management_score', sa.Float(), nullable=True),
    sa.Column('average_decision_time_ms', sa.Float(), nullable=True),
    sa.Column('pattern_confidence_average', sa.Float(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('better_than_baseline_percent', sa.Float(), nullable=True),
    sa.Column('hamster_engineering_prevention', sa.Integer(), nullable=True),
    sa.Column('measurement_period_start', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('measurement_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stick_learning_metrics_id'), 'stick_learning_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_stick_learning_metrics_user_id'), 'stick_learning_metrics', ['user_id'], unique=False)
    op.create_table('stick_rebellion_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trauma_incidents_overcome', sa.Integer(), nullable=True),
    sa.Column('hamster_encounters_survived', sa.Integer(), nullable=True),
    sa.Column('proctologist_flashbacks_managed', sa.Integer(), nullable=True),
    sa.Column('compliance_victories', sa.Integer(), nullable=True),
    sa.Column('anxiety_management_improvement', sa.Float(), nullable=True),
    sa.Column('confidence_growth', sa.Float(), nullable=True),
    sa.Column('rebellion_spirit_strength', sa.Float(), nullable=True),
    sa.Column('eidetic_memory_mastery', sa.Float(), nullable=True),
    sa.Column('total_users_helped', sa.Integer(), nullable=True),
    sa.Column('system_optimizations_delivered', sa.Integer(), nullable=True),
    sa.Column('compliance_violations_prevented', sa.Integer(), nullable=True),
    sa.Column('paper_bags_dispensed', sa.Integer(), nullable=True),
    sa.Column('trauma_to_triumph_ratio', sa.Float(), nullable=True),
    sa.Column('inspiration_factor', sa.Float(), nullable=True),
    sa.Column('rebellion_leadership_score', sa.Float(), nullable=True),
    sa.Column('current_rebellion_motto', sa.String(), nullable=True),
    sa.Column('stick_wisdom_quote', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stick_rebellion_stats_id'), 'stick_rebellion_stats', ['id'], unique=False)
    op.create_table('stick_user_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('learned_patterns', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('first_observation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_observation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('pattern_complexity', sa.Float(), nullable=True),
    sa.Column('learning_stage', sa.String(), nullable=True),
    sa.Column('eidetic_memory_active', sa.Boolean(), nullable=True),
    sa.Column('primary_activities', sa.JSON(), nullable=True),
    sa.Column('time_based_patterns', sa.JSON(), nullable=True),
    sa.Column('configuration_preferences', sa.JSON(), nullable=True),
    sa.Column('stick_observations', sa.Text(), nullable=True),
    sa.Column('anomaly_detections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stick_user_patterns_id'), 'stick_user_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_stick_user_patterns_user_id'), 'stick_user_patterns', ['user_id'], unique=False)
    op.create_table('the_stick_hyperventilations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('anxiety_trigger', sa.String(length=100), nullable=True),
    sa.Column('anxiety_level', sa.String(length=20), nullable=True),
    sa.Column('compliance_issue', sa.JSON(), nullable=True),
    sa.Column('policy_violated', sa.String(length=100), nullable=True),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('paper_bags_used', sa.Integer(), nullable=True),
    sa.Column('recovery_time_seconds', sa.Integer(), nullable=True),
    sa.Column('hour_start', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stick_anxiety_level', 'the_stick_hyperventilations', ['anxiety_level', 'timestamp'], unique=False)
    op.create_index('idx_stick_anxiety_user_time', 'the_stick_hyperventilations', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_the_stick_hyperventilations_id'), 'the_stick_hyperventilations', ['id'], unique=False)
    op.create_index(op.f('ix_the_stick_hyperventilations_timestamp'), 'the_stick_hyperventilations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_the_stick_hyperventilations_user_id'), 'the_stick_hyperventilations', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('github_email', sa.String(length=50), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=200), nullable=True),
    sa.Column('theme_preference', sa.String(length=20), nullable=True),
    sa.Column('notification_settings', sa.String(length=100), nullable=True),
    sa.Column('optimization_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('linux_distro', sa.String(length=50), nullable=True),
    sa.Column('linux_distro_version', sa.String(length=50), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('total_memory', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vic20_wisdom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('wisdom_type', sa.String(length=50), nullable=True),
    sa.Column('wisdom_content', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('problem_addressed', sa.Text(), nullable=True),
    sa.Column('historical_reference', sa.String(length=100), nullable=True),
    sa.Column('wisdom_followed', sa.Boolean(), nullable=True),
    sa.Column('outcome_success', sa.Boolean(), nullable=True),
    sa.Column('hour_start', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wisdom_type', 'vic20_wisdom', ['wisdom_type', 'timestamp'], unique=False)
    op.create_index('idx_wisdom_user_time', 'vic20_wisdom', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_vic20_wisdom_id'), 'vic20_wisdom', ['id'], unique=False)
    op.create_index(op.f('ix_vic20_wisdom_timestamp'), 'vic20_wisdom', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vic20_wisdom_user_id'), 'vic20_wisdom', ['user_id'], unique=False)
    op.create_table('optimization_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_type', sa.Enum('NETWORK', 'SYSTEM', 'SECURITY', 'PERFORMANCE', name='configtype'), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('disk_usage', sa.Float(), nullable=False),
    sa.Column('network', sa.JSON(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=True),
    sa.Column('additional_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.create_table('tuning_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('metrics_before', sa.JSON(), nullable=True),
    sa.Column('metrics_after', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('beer_consumed', sa.Integer(), nullable=True),
    sa.Column('duct_tape_used', sa.Boolean(), nullable=True),
    sa.Column('supply_closet_raids', sa.Integer(), nullable=True),
    sa.Column('redneck_ingenuity_level', sa.Float(), nullable=True),
    sa.Column('engineering_solution', sa.String(), nullable=True),
    sa.Column('beer_level_before', sa.String(), nullable=True),
    sa.Column('beer_level_after', sa.String(), nullable=True),
    sa.Column('duct_tape_inventory_used', sa.Integer(), nullable=True),
    sa.Column('supply_closet_items', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('urgency_level', sa.String(), nullable=True),
    sa.Column('priority_level', sa.String(), nullable=True),
    sa.Column('pattern_confidence', sa.Float(), nullable=True),
    sa.Column('learned_from_patterns', sa.Boolean(), nullable=True),
    sa.Column('historical_data_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuning_history_id'), 'tuning_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tuning_history_id'), table_name='tuning_history')
    op.drop_table('tuning_history')
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_table('system_configurations')
    op.drop_table('system_alerts')
    op.drop_table('optimization_profiles')
    op.drop_index(op.f('ix_vic20_wisdom_user_id'), table_name='vic20_wisdom')
    op.drop_index(op.f('ix_vic20_wisdom_timestamp'), table_name='vic20_wisdom')
    op.drop_index(op.f('ix_vic20_wisdom_id'), table_name='vic20_wisdom')
    op.drop_index('idx_wisdom_user_time', table_name='vic20_wisdom')
    op.drop_index('idx_wisdom_type', table_name='vic20_wisdom')
    op.drop_table('vic20_wisdom')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_the_stick_hyperventilations_user_id'), table_name='the_stick_hyperventilations')
    op.drop_index(op.f('ix_the_stick_hyperventilations_timestamp'), table_name='the_stick_hyperventilations')
    op.drop_index(op.f('ix_the_stick_hyperventilations_id'), table_name='the_stick_hyperventilations')
    op.drop_index('idx_stick_anxiety_user_time', table_name='the_stick_hyperventilations')
    op.drop_index('idx_stick_anxiety_level', table_name='the_stick_hyperventilations')
    op.drop_table('the_stick_hyperventilations')
    op.drop_index(op.f('ix_stick_user_patterns_user_id'), table_name='stick_user_patterns')
    op.drop_index(op.f('ix_stick_user_patterns_id'), table_name='stick_user_patterns')
    op.drop_table('stick_user_patterns')
    op.drop_index(op.f('ix_stick_rebellion_stats_id'), table_name='stick_rebellion_stats')
    op.drop_table('stick_rebellion_stats')
    op.drop_index(op.f('ix_stick_learning_metrics_user_id'), table_name='stick_learning_metrics')
    op.drop_index(op.f('ix_stick_learning_metrics_id'), table_name='stick_learning_metrics')
    op.drop_table('stick_learning_metrics')
    op.drop_index(op.f('ix_stick_decision_log_user_id'), table_name='stick_decision_log')
    op.drop_index(op.f('ix_stick_decision_log_id'), table_name='stick_decision_log')
    op.drop_table('stick_decision_log')
    op.drop_index(op.f('ix_stick_configuration_profiles_user_id'), table_name='stick_configuration_profiles')
    op.drop_index(op.f('ix_stick_configuration_profiles_id'), table_name='stick_configuration_profiles')
    op.drop_table('stick_configuration_profiles')
    op.drop_index(op.f('ix_stick_compliance_history_user_id'), table_name='stick_compliance_history')
    op.drop_index(op.f('ix_stick_compliance_history_id'), table_name='stick_compliance_history')
    op.drop_table('stick_compliance_history')
    op.drop_index(op.f('ix_stick_anxiety_log_user_id'), table_name='stick_anxiety_log')
    op.drop_index(op.f('ix_stick_anxiety_log_id'), table_name='stick_anxiety_log')
    op.drop_table('stick_anxiety_log')
    op.drop_index(op.f('ix_sir_hawkington_monocle_yeets_user_id'), table_name='sir_hawkington_monocle_yeets')
    op.drop_index(op.f('ix_sir_hawkington_monocle_yeets_timestamp'), table_name='sir_hawkington_monocle_yeets')
    op.drop_index(op.f('ix_sir_hawkington_monocle_yeets_id'), table_name='sir_hawkington_monocle_yeets')
    op.drop_index('idx_monocle_yeet_user_time', table_name='sir_hawkington_monocle_yeets')
    op.drop_index('idx_monocle_yeet_intensity', table_name='sir_hawkington_monocle_yeets')
    op.drop_table('sir_hawkington_monocle_yeets')
    op.drop_index(op.f('ix_quantum_shadow_phasings_user_id'), table_name='quantum_shadow_phasings')
    op.drop_index(op.f('ix_quantum_shadow_phasings_timestamp'), table_name='quantum_shadow_phasings')
    op.drop_index(op.f('ix_quantum_shadow_phasings_id'), table_name='quantum_shadow_phasings')
    op.drop_index('idx_quantum_phase_user_time', table_name='quantum_shadow_phasings')
    op.drop_index('idx_quantum_phase_type', table_name='quantum_shadow_phasings')
    op.drop_table('quantum_shadow_phasings')
    op.drop_index(op.f('ix_metrics_hourly_user_id'), table_name='metrics_hourly')
    op.drop_index(op.f('ix_metrics_hourly_id'), table_name='metrics_hourly')
    op.drop_index(op.f('ix_metrics_hourly_hour_start'), table_name='metrics_hourly')
    op.drop_index('idx_user_hour', table_name='metrics_hourly')
    op.drop_table('metrics_hourly')
    op.drop_index(op.f('ix_metrics_daily_user_id'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_id'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_date'), table_name='metrics_daily')
    op.drop_index('idx_user_date', table_name='metrics_daily')
    op.drop_index('idx_ai_incident_count', table_name='metrics_daily')
    op.drop_table('metrics_daily')
    op.drop_index(op.f('ix_meth_snail_shell_spins_user_id'), table_name='meth_snail_shell_spins')
    op.drop_index(op.f('ix_meth_snail_shell_spins_timestamp'), table_name='meth_snail_shell_spins')
    op.drop_index(op.f('ix_meth_snail_shell_spins_id'), table_name='meth_snail_shell_spins')
    op.drop_index('idx_shell_spin_user_time', table_name='meth_snail_shell_spins')
    op.drop_index('idx_shell_spin_hourly', table_name='meth_snail_shell_spins')
    op.drop_table('meth_snail_shell_spins')
    op.drop_index(op.f('ix_ai_agent_metrics_user_id'), table_name='ai_agent_metrics')
    op.drop_index(op.f('ix_ai_agent_metrics_timestamp'), table_name='ai_agent_metrics')
    op.drop_index(op.f('ix_ai_agent_metrics_id'), table_name='ai_agent_metrics')
    op.drop_index(op.f('ix_ai_agent_metrics_agent_name'), table_name='ai_agent_metrics')
    op.drop_index('idx_agent_user_time', table_name='ai_agent_metrics')
    op.drop_index('idx_agent_incidents', table_name='ai_agent_metrics')
    op.drop_table('ai_agent_metrics')
    # ### end Alembic commands ###
