"""add three-tier agent event system

Revision ID: 5dea6e23a9b2
Revises: dcdfe9d57387
Create Date: 2025-10-14 12:52:51.421088
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dea6e23a9b2'
down_revision: Union[str, None] = 'dcdfe9d57387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_event_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('agent_state', sa.String(length=50), nullable=True),
    sa.Column('date_partition', sa.Date(), nullable=False),
    sa.Column('ttl_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_event_log'))
    )
    op.create_index('idx_agent_event_time', 'agent_event_log', ['agent_name', 'event_type', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_date_partition', 'agent_event_log', ['date_partition'], unique=False, postgresql_using='btree')
    op.create_index('idx_event_data_gin', 'agent_event_log', ['event_data'], unique=False, postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.create_index('idx_event_type_time', 'agent_event_log', ['event_type', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_severity_time', 'agent_event_log', ['severity', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_ttl_cleanup', 'agent_event_log', ['ttl_expires_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_user_event_time', 'agent_event_log', ['user_id', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_agent_event_log_agent_name'), 'agent_event_log', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_event_log_date_partition'), 'agent_event_log', ['date_partition'], unique=False)
    op.create_index(op.f('ix_agent_event_log_event_type'), 'agent_event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_event_log_severity'), 'agent_event_log', ['severity'], unique=False)
    op.create_index(op.f('ix_agent_event_log_timestamp'), 'agent_event_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_event_log_ttl_expires_at'), 'agent_event_log', ['ttl_expires_at'], unique=False)
    op.create_index(op.f('ix_agent_event_log_user_id'), 'agent_event_log', ['user_id'], unique=False)
    op.create_table('agent_significant_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('significance_reason', sa.String(length=255), nullable=False),
    sa.Column('learned_pattern_id', sa.String(length=36), nullable=True),
    sa.Column('contributed_to_learning', sa.Boolean(), nullable=True),
    sa.Column('never_forget', sa.Boolean(), nullable=True),
    sa.Column('times_referenced', sa.Integer(), nullable=True),
    sa.Column('last_referenced', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_significant_events'))
    )
    op.create_index('idx_most_referenced', 'agent_significant_events', ['times_referenced', 'agent_name'], unique=False, postgresql_using='btree')
    op.create_index('idx_never_forget', 'agent_significant_events', ['never_forget', 'agent_name'], unique=False, postgresql_using='btree')
    op.create_index('idx_significant_agent_type', 'agent_significant_events', ['agent_name', 'event_type', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_significant_data_gin', 'agent_significant_events', ['event_data'], unique=False, postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.create_index('idx_user_significant', 'agent_significant_events', ['user_id', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_agent_significant_events_agent_name'), 'agent_significant_events', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_significant_events_event_type'), 'agent_significant_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_significant_events_never_forget'), 'agent_significant_events', ['never_forget'], unique=False)
    op.create_index(op.f('ix_agent_significant_events_timestamp'), 'agent_significant_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_significant_events_user_id'), 'agent_significant_events', ['user_id'], unique=False)
    op.create_table('agent_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('agent_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_statistics'))
    )
    op.create_index('idx_agent_period', 'agent_statistics', ['agent_name', 'period_type', 'period_start'], unique=False, postgresql_using='btree')
    op.create_index('idx_period_range', 'agent_statistics', ['period_type', 'period_start', 'period_end'], unique=False, postgresql_using='btree')
    op.create_index('idx_user_period', 'agent_statistics', ['user_id', 'period_type', 'period_start'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_agent_statistics_agent_name'), 'agent_statistics', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_statistics_period_start'), 'agent_statistics', ['period_start'], unique=False)
    op.create_index(op.f('ix_agent_statistics_user_id'), 'agent_statistics', ['user_id'], unique=False)
    op.add_column('hamsters_memory_bank', sa.Column('supply_raids_count', sa.Integer(), nullable=True))
    op.add_column('hamsters_memory_bank', sa.Column('beer_consumed_count', sa.Integer(), nullable=True))
    op.add_column('hamsters_memory_bank', sa.Column('duct_tape_used_count', sa.Integer(), nullable=True))
    op.add_column('hamsters_memory_bank', sa.Column('interventions_count', sa.Integer(), nullable=True))
    op.add_column('hamsters_memory_bank', sa.Column('last_raid_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hamsters_memory_bank', sa.Column('last_intervention_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meth_snail_memory_bank', sa.Column('energy_drinks_consumed_count', sa.Integer(), nullable=True))
    op.add_column('meth_snail_memory_bank', sa.Column('shell_spins_count', sa.Integer(), nullable=True))
    op.add_column('meth_snail_memory_bank', sa.Column('optimizations_applied_count', sa.Integer(), nullable=True))
    op.add_column('meth_snail_memory_bank', sa.Column('last_energy_drink_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meth_snail_memory_bank', sa.Column('last_shell_spin_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quantum_shadow_people_memory_bank', sa.Column('dimensional_shifts_count', sa.Integer(), nullable=True))
    op.add_column('quantum_shadow_people_memory_bank', sa.Column('quantum_fixes_count', sa.Integer(), nullable=True))
    op.add_column('quantum_shadow_people_memory_bank', sa.Column('tequila_jello_shots_count', sa.Integer(), nullable=True))
    op.add_column('quantum_shadow_people_memory_bank', sa.Column('last_dimensional_shift_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quantum_shadow_people_memory_bank', sa.Column('last_quantum_fix_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sir_hawkington_memory_bank', sa.Column('monocle_yeets_count', sa.Integer(), nullable=True))
    op.add_column('sir_hawkington_memory_bank', sa.Column('alerts_generated_count', sa.Integer(), nullable=True))
    op.add_column('sir_hawkington_memory_bank', sa.Column('triage_decisions_count', sa.Integer(), nullable=True))
    op.add_column('sir_hawkington_memory_bank', sa.Column('last_yeet_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sir_hawkington_memory_bank', sa.Column('last_alert_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('the_stick_memory_bank', sa.Column('paper_bags_consumed_count', sa.Integer(), nullable=True))
    op.add_column('the_stick_memory_bank', sa.Column('hamster_encounters_count', sa.Integer(), nullable=True))
    op.add_column('the_stick_memory_bank', sa.Column('anxiety_spikes_count', sa.Integer(), nullable=True))
    op.add_column('the_stick_memory_bank', sa.Column('last_paper_bag_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('the_stick_memory_bank', sa.Column('last_hamster_encounter_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vic20_memory_bank', sa.Column('coordinations_count', sa.Integer(), nullable=True))
    op.add_column('vic20_memory_bank', sa.Column('mediations_count', sa.Integer(), nullable=True))
    op.add_column('vic20_memory_bank', sa.Column('wisdom_dispensed_count', sa.Integer(), nullable=True))
    op.add_column('vic20_memory_bank', sa.Column('last_coordination_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vic20_memory_bank', sa.Column('last_wisdom_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vic20_memory_bank', 'last_wisdom_timestamp')
    op.drop_column('vic20_memory_bank', 'last_coordination_timestamp')
    op.drop_column('vic20_memory_bank', 'wisdom_dispensed_count')
    op.drop_column('vic20_memory_bank', 'mediations_count')
    op.drop_column('vic20_memory_bank', 'coordinations_count')
    op.drop_column('the_stick_memory_bank', 'last_hamster_encounter_timestamp')
    op.drop_column('the_stick_memory_bank', 'last_paper_bag_timestamp')
    op.drop_column('the_stick_memory_bank', 'anxiety_spikes_count')
    op.drop_column('the_stick_memory_bank', 'hamster_encounters_count')
    op.drop_column('the_stick_memory_bank', 'paper_bags_consumed_count')
    op.drop_column('sir_hawkington_memory_bank', 'last_alert_timestamp')
    op.drop_column('sir_hawkington_memory_bank', 'last_yeet_timestamp')
    op.drop_column('sir_hawkington_memory_bank', 'triage_decisions_count')
    op.drop_column('sir_hawkington_memory_bank', 'alerts_generated_count')
    op.drop_column('sir_hawkington_memory_bank', 'monocle_yeets_count')
    op.drop_column('quantum_shadow_people_memory_bank', 'last_quantum_fix_timestamp')
    op.drop_column('quantum_shadow_people_memory_bank', 'last_dimensional_shift_timestamp')
    op.drop_column('quantum_shadow_people_memory_bank', 'tequila_jello_shots_count')
    op.drop_column('quantum_shadow_people_memory_bank', 'quantum_fixes_count')
    op.drop_column('quantum_shadow_people_memory_bank', 'dimensional_shifts_count')
    op.drop_column('meth_snail_memory_bank', 'last_shell_spin_timestamp')
    op.drop_column('meth_snail_memory_bank', 'last_energy_drink_timestamp')
    op.drop_column('meth_snail_memory_bank', 'optimizations_applied_count')
    op.drop_column('meth_snail_memory_bank', 'shell_spins_count')
    op.drop_column('meth_snail_memory_bank', 'energy_drinks_consumed_count')
    op.drop_column('hamsters_memory_bank', 'last_intervention_timestamp')
    op.drop_column('hamsters_memory_bank', 'last_raid_timestamp')
    op.drop_column('hamsters_memory_bank', 'interventions_count')
    op.drop_column('hamsters_memory_bank', 'duct_tape_used_count')
    op.drop_column('hamsters_memory_bank', 'beer_consumed_count')
    op.drop_column('hamsters_memory_bank', 'supply_raids_count')
    op.drop_index(op.f('ix_agent_statistics_user_id'), table_name='agent_statistics')
    op.drop_index(op.f('ix_agent_statistics_period_start'), table_name='agent_statistics')
    op.drop_index(op.f('ix_agent_statistics_agent_name'), table_name='agent_statistics')
    op.drop_index('idx_user_period', table_name='agent_statistics', postgresql_using='btree')
    op.drop_index('idx_period_range', table_name='agent_statistics', postgresql_using='btree')
    op.drop_index('idx_agent_period', table_name='agent_statistics', postgresql_using='btree')
    op.drop_table('agent_statistics')
    op.drop_index(op.f('ix_agent_significant_events_user_id'), table_name='agent_significant_events')
    op.drop_index(op.f('ix_agent_significant_events_timestamp'), table_name='agent_significant_events')
    op.drop_index(op.f('ix_agent_significant_events_never_forget'), table_name='agent_significant_events')
    op.drop_index(op.f('ix_agent_significant_events_event_type'), table_name='agent_significant_events')
    op.drop_index(op.f('ix_agent_significant_events_agent_name'), table_name='agent_significant_events')
    op.drop_index('idx_user_significant', table_name='agent_significant_events', postgresql_using='btree')
    op.drop_index('idx_significant_data_gin', table_name='agent_significant_events', postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.drop_index('idx_significant_agent_type', table_name='agent_significant_events', postgresql_using='btree')
    op.drop_index('idx_never_forget', table_name='agent_significant_events', postgresql_using='btree')
    op.drop_index('idx_most_referenced', table_name='agent_significant_events', postgresql_using='btree')
    op.drop_table('agent_significant_events')
    op.drop_index(op.f('ix_agent_event_log_user_id'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_ttl_expires_at'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_timestamp'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_severity'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_event_type'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_date_partition'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_agent_name'), table_name='agent_event_log')
    op.drop_index('idx_user_event_time', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_ttl_cleanup', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_severity_time', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_event_type_time', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_event_data_gin', table_name='agent_event_log', postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.drop_index('idx_date_partition', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_agent_event_time', table_name='agent_event_log', postgresql_using='btree')
    op.drop_table('agent_event_log')
    # ### end Alembic commands ###
