"""baseline migration for memory system

Revision ID: 1f202b4abd39
Revises: 
Create Date: 2025-08-23 08:04:40.724101
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f202b4abd39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_global_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pattern_key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_global_patterns'))
    )
    op.create_index(op.f('ix_agent_global_patterns_pattern_key'), 'agent_global_patterns', ['pattern_key'], unique=False)
    op.create_table('agent_learning_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_agent', sa.String(length=50), nullable=False),
    sa.Column('target_agent', sa.String(length=50), nullable=False),
    sa.Column('source_memory_id', sa.String(length=36), nullable=False),
    sa.Column('learning_type', sa.String(length=100), nullable=False),
    sa.Column('adaptation_method', sa.JSON(), nullable=True),
    sa.Column('application_context', sa.JSON(), nullable=True),
    sa.Column('transfer_success', sa.Boolean(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('improvement_measured', sa.Float(), nullable=True),
    sa.Column('validated_by_stick', sa.Boolean(), nullable=True),
    sa.Column('cross_validation_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_learning_interactions')),
    sa.UniqueConstraint('interaction_id', name=op.f('uq_agent_learning_interactions_interaction_id'))
    )
    op.create_index('idx_learning_effectiveness', 'agent_learning_interactions', ['effectiveness_score', 'transfer_success'], unique=False)
    op.create_index('idx_learning_transfer', 'agent_learning_interactions', ['source_agent', 'target_agent', 'learning_type'], unique=False)
    op.create_index(op.f('ix_agent_learning_interactions_source_agent'), 'agent_learning_interactions', ['source_agent'], unique=False)
    op.create_index(op.f('ix_agent_learning_interactions_target_agent'), 'agent_learning_interactions', ['target_agent'], unique=False)
    op.create_index(op.f('ix_agent_learning_interactions_timestamp'), 'agent_learning_interactions', ['timestamp'], unique=False)
    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_memories'))
    )
    op.create_index(op.f('ix_agent_memories_agent_name'), 'agent_memories', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_memories_memory_type'), 'agent_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_agent_memories_timestamp'), 'agent_memories', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_memories_user_id'), 'agent_memories', ['user_id'], unique=False)
    op.create_index('ix_mem_user_agent_type_time', 'agent_memories', ['user_id', 'agent_name', 'memory_type', 'timestamp'], unique=False)
    op.create_table('central_memory_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('subject_kind', sa.String(length=50), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('parent_memory_id', sa.String(length=36), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('string_value', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('agent_metadata', sa.JSON(), nullable=True),
    sa.Column('relevant_agents', sa.String(length=255), nullable=True),
    sa.Column('cross_agent_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_count', sa.Integer(), nullable=True),
    sa.Column('stick_anxiety_level', sa.Float(), nullable=True),
    sa.Column('never_forget', sa.Boolean(), nullable=True),
    sa.Column('times_referenced', sa.Integer(), nullable=True),
    sa.Column('last_referenced', sa.DateTime(), nullable=True),
    sa.Column('successful_applications', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_memory_id'], ['central_memory_bank.memory_id'], name=op.f('fk_central_memory_bank_parent_memory_id_central_memory_bank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_central_memory_bank')),
    sa.UniqueConstraint('memory_id', name=op.f('uq_central_memory_bank_memory_id'))
    )
    op.create_index('idx_agent_memories', 'central_memory_bank', ['agent_name', 'event_type'], unique=False)
    op.create_index('idx_agent_user', 'central_memory_bank', ['agent_name', 'user_id'], unique=False)
    op.create_index('idx_cross_agent', 'central_memory_bank', ['relevant_agents', 'cross_agent_validated'], unique=False)
    op.create_index('idx_event_timestamp', 'central_memory_bank', ['event_type', 'occurred_at'], unique=False)
    op.create_index('idx_memory_importance', 'central_memory_bank', ['priority', 'never_forget'], unique=False)
    op.create_index('idx_priority_access', 'central_memory_bank', ['priority', 'last_referenced'], unique=False)
    op.create_index('idx_subject_reference', 'central_memory_bank', ['subject_kind', 'subject_id'], unique=False)
    op.create_index('idx_user_memories', 'central_memory_bank', ['user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_central_memory_bank_agent_name'), 'central_memory_bank', ['agent_name'], unique=False)
    op.create_index(op.f('ix_central_memory_bank_created_at'), 'central_memory_bank', ['created_at'], unique=False)
    op.create_index(op.f('ix_central_memory_bank_event_type'), 'central_memory_bank', ['event_type'], unique=False)
    op.create_index(op.f('ix_central_memory_bank_occurred_at'), 'central_memory_bank', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_central_memory_bank_priority'), 'central_memory_bank', ['priority'], unique=False)
    op.create_index(op.f('ix_central_memory_bank_subject_id'), 'central_memory_bank', ['subject_id'], unique=False)
    op.create_index(op.f('ix_central_memory_bank_subject_kind'), 'central_memory_bank', ['subject_kind'], unique=False)
    op.create_index(op.f('ix_central_memory_bank_user_id'), 'central_memory_bank', ['user_id'], unique=False)
    op.create_table('memory_bank_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_memories', sa.Integer(), nullable=True),
    sa.Column('central_bank_memories', sa.Integer(), nullable=True),
    sa.Column('cross_agent_learnings', sa.Integer(), nullable=True),
    sa.Column('hawkington_memories', sa.Integer(), nullable=True),
    sa.Column('snail_memories', sa.Integer(), nullable=True),
    sa.Column('hamsters_memories', sa.Integer(), nullable=True),
    sa.Column('qsp_memories', sa.Integer(), nullable=True),
    sa.Column('vic20_memories', sa.Integer(), nullable=True),
    sa.Column('stick_memories', sa.Integer(), nullable=True),
    sa.Column('successful_transfers', sa.Integer(), nullable=True),
    sa.Column('failed_transfers', sa.Integer(), nullable=True),
    sa.Column('average_effectiveness_score', sa.Float(), nullable=True),
    sa.Column('memory_bank_health_score', sa.Float(), nullable=True),
    sa.Column('stick_anxiety_level', sa.Float(), nullable=True),
    sa.Column('memory_retrieval_speed_ms', sa.Float(), nullable=True),
    sa.Column('cross_agent_query_speed_ms', sa.Float(), nullable=True),
    sa.Column('learning_application_success_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_bank_metadata'))
    )
    op.create_index('idx_memory_effectiveness', 'memory_bank_metadata', ['average_effectiveness_score', 'successful_transfers'], unique=False)
    op.create_index('idx_memory_health', 'memory_bank_metadata', ['memory_bank_health_score', 'timestamp'], unique=False)
    op.create_index(op.f('ix_memory_bank_metadata_timestamp'), 'memory_bank_metadata', ['timestamp'], unique=False)
    op.create_table('metrics_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('daily_meth_snail_shell_spins', sa.Integer(), nullable=True),
    sa.Column('daily_hawkington_monocle_yeets', sa.Integer(), nullable=True),
    sa.Column('daily_stick_hyperventilations', sa.Integer(), nullable=True),
    sa.Column('daily_quantum_shadow_phasings', sa.Integer(), nullable=True),
    sa.Column('daily_vic20_wisdom_dispensed', sa.Integer(), nullable=True),
    sa.Column('daily_ai_incident_count', sa.Integer(), nullable=True),
    sa.Column('daily_ai_incident_type', sa.String(), nullable=True),
    sa.Column('daily_ai_incident_reason', sa.String(), nullable=True),
    sa.Column('daily_ai_incident_data_quality_score', sa.Float(), nullable=True),
    sa.Column('daily_ai_incident_summary', sa.JSON(), nullable=True),
    sa.Column('cpu_avg', sa.Float(), nullable=True),
    sa.Column('cpu_peak_time', sa.DateTime(), nullable=True),
    sa.Column('cpu_peak_value', sa.Float(), nullable=True),
    sa.Column('memory_avg', sa.Float(), nullable=True),
    sa.Column('memory_peak_time', sa.DateTime(), nullable=True),
    sa.Column('memory_peak_value', sa.Float(), nullable=True),
    sa.Column('disk_avg', sa.Float(), nullable=True),
    sa.Column('network_bytes_total', sa.Float(), nullable=True),
    sa.Column('usage_pattern', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_daily'))
    )
    op.create_index('idx_ai_incident_count', 'metrics_daily', ['daily_ai_incident_count', 'daily_ai_incident_type', 'daily_ai_incident_reason'], unique=False)
    op.create_index('idx_user_date', 'metrics_daily', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_metrics_daily_date'), 'metrics_daily', ['date'], unique=False)
    op.create_index(op.f('ix_metrics_daily_id'), 'metrics_daily', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_daily_user_id'), 'metrics_daily', ['user_id'], unique=False)
    op.create_table('metrics_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hour_start', sa.DateTime(), nullable=False),
    sa.Column('meth_snail_shell_spins', sa.Integer(), nullable=True),
    sa.Column('hawkington_monocle_yeets', sa.Integer(), nullable=True),
    sa.Column('stick_hyperventilations', sa.Integer(), nullable=True),
    sa.Column('quantum_shadow_phasings', sa.Integer(), nullable=True),
    sa.Column('vic20_wisdom_dispensed', sa.Integer(), nullable=True),
    sa.Column('ai_agent_incident_count', sa.Integer(), nullable=True),
    sa.Column('ai_agent_incident_type', sa.String(), nullable=True),
    sa.Column('ai_agent_incident_reason', sa.String(), nullable=True),
    sa.Column('ai_agent_incident_data_quality_score', sa.Float(), nullable=True),
    sa.Column('ai_agent_incident_summary', sa.JSON(), nullable=True),
    sa.Column('cpu_avg', sa.Float(), nullable=True),
    sa.Column('cpu_max', sa.Float(), nullable=True),
    sa.Column('cpu_min', sa.Float(), nullable=True),
    sa.Column('memory_avg', sa.Float(), nullable=True),
    sa.Column('memory_max', sa.Float(), nullable=True),
    sa.Column('memory_min', sa.Float(), nullable=True),
    sa.Column('disk_avg', sa.Float(), nullable=True),
    sa.Column('network_bytes_total', sa.Float(), nullable=True),
    sa.Column('ai_events', sa.JSON(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_hourly'))
    )
    op.create_index('idx_user_hour', 'metrics_hourly', ['user_id', 'hour_start'], unique=False)
    op.create_index(op.f('ix_metrics_hourly_hour_start'), 'metrics_hourly', ['hour_start'], unique=False)
    op.create_index(op.f('ix_metrics_hourly_id'), 'metrics_hourly', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_hourly_user_id'), 'metrics_hourly', ['user_id'], unique=False)
    op.create_table('user_learning_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interaction_pattern', sa.JSON(), nullable=True),
    sa.Column('learning_preference', sa.JSON(), nullable=True),
    sa.Column('response_patterns', sa.JSON(), nullable=True),
    sa.Column('most_effective_agent', sa.String(length=50), nullable=True),
    sa.Column('communication_style_preference', sa.JSON(), nullable=True),
    sa.Column('complexity_tolerance', sa.Float(), nullable=True),
    sa.Column('skill_improvement_areas', sa.JSON(), nullable=True),
    sa.Column('knowledge_gaps', sa.JSON(), nullable=True),
    sa.Column('success_patterns', sa.JSON(), nullable=True),
    sa.Column('agent_effectiveness_ranking', sa.JSON(), nullable=True),
    sa.Column('collaborative_preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_learning_patterns')),
    sa.UniqueConstraint('pattern_id', name=op.f('uq_user_learning_patterns_pattern_id'))
    )
    op.create_index('idx_user_learning', 'user_learning_patterns', ['learning_preference', 'complexity_tolerance'], unique=False)
    op.create_index('idx_user_patterns', 'user_learning_patterns', ['user_id', 'most_effective_agent'], unique=False)
    op.create_index(op.f('ix_user_learning_patterns_timestamp'), 'user_learning_patterns', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_learning_patterns_user_id'), 'user_learning_patterns', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('onboarding_progress', sa.Integer(), nullable=True),
    sa.Column('onboarding_data', sa.JSON(), nullable=True),
    sa.Column('onboarding_started_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_last_step_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_abandoned_count', sa.Integer(), nullable=False),
    sa.Column('onboarding_step_timestamps', sa.JSON(), nullable=True),
    sa.Column('onboarding_abandonment_reasons', sa.JSON(), nullable=True),
    sa.Column('onboarding_device_info', sa.JSON(), nullable=True),
    sa.Column('onboarding_referral_source', sa.String(length=100), nullable=True),
    sa.Column('preview_agent_selected', sa.String(length=20), nullable=True),
    sa.Column('preview_started_at', sa.DateTime(), nullable=True),
    sa.Column('preview_expires_at', sa.DateTime(), nullable=True),
    sa.Column('preview_conversion_emails_sent', sa.JSON(), nullable=True),
    sa.Column('preview_converted_at', sa.DateTime(), nullable=True),
    sa.Column('email_campaign_responses', sa.JSON(), nullable=True),
    sa.Column('last_engagement_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=50), nullable=True),
    sa.Column('system_name', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('agent_preferences', sa.JSON(), nullable=True),
    sa.Column('monitoring_preferences', sa.JSON(), nullable=True),
    sa.Column('system_profile', sa.JSON(), nullable=True),
    sa.Column('agent_installed', sa.Boolean(), nullable=True),
    sa.Column('agent_version', sa.String(length=20), nullable=True),
    sa.Column('installation_method', sa.String(length=50), nullable=True),
    sa.Column('permissions_granted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_enterprise', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('patterns_learned', sa.Integer(), nullable=True),
    sa.Column('decisions_made', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('disk_usage', sa.Float(), nullable=False),
    sa.Column('network', sa.JSON(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=True),
    sa.Column('additional_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_system_metrics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_metrics'))
    )
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_learning_patterns_user_id'), table_name='user_learning_patterns')
    op.drop_index(op.f('ix_user_learning_patterns_timestamp'), table_name='user_learning_patterns')
    op.drop_index('idx_user_patterns', table_name='user_learning_patterns')
    op.drop_index('idx_user_learning', table_name='user_learning_patterns')
    op.drop_table('user_learning_patterns')
    op.drop_index(op.f('ix_metrics_hourly_user_id'), table_name='metrics_hourly')
    op.drop_index(op.f('ix_metrics_hourly_id'), table_name='metrics_hourly')
    op.drop_index(op.f('ix_metrics_hourly_hour_start'), table_name='metrics_hourly')
    op.drop_index('idx_user_hour', table_name='metrics_hourly')
    op.drop_table('metrics_hourly')
    op.drop_index(op.f('ix_metrics_daily_user_id'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_id'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_date'), table_name='metrics_daily')
    op.drop_index('idx_user_date', table_name='metrics_daily')
    op.drop_index('idx_ai_incident_count', table_name='metrics_daily')
    op.drop_table('metrics_daily')
    op.drop_index(op.f('ix_memory_bank_metadata_timestamp'), table_name='memory_bank_metadata')
    op.drop_index('idx_memory_health', table_name='memory_bank_metadata')
    op.drop_index('idx_memory_effectiveness', table_name='memory_bank_metadata')
    op.drop_table('memory_bank_metadata')
    op.drop_index(op.f('ix_central_memory_bank_user_id'), table_name='central_memory_bank')
    op.drop_index(op.f('ix_central_memory_bank_subject_kind'), table_name='central_memory_bank')
    op.drop_index(op.f('ix_central_memory_bank_subject_id'), table_name='central_memory_bank')
    op.drop_index(op.f('ix_central_memory_bank_priority'), table_name='central_memory_bank')
    op.drop_index(op.f('ix_central_memory_bank_occurred_at'), table_name='central_memory_bank')
    op.drop_index(op.f('ix_central_memory_bank_event_type'), table_name='central_memory_bank')
    op.drop_index(op.f('ix_central_memory_bank_created_at'), table_name='central_memory_bank')
    op.drop_index(op.f('ix_central_memory_bank_agent_name'), table_name='central_memory_bank')
    op.drop_index('idx_user_memories', table_name='central_memory_bank')
    op.drop_index('idx_subject_reference', table_name='central_memory_bank')
    op.drop_index('idx_priority_access', table_name='central_memory_bank')
    op.drop_index('idx_memory_importance', table_name='central_memory_bank')
    op.drop_index('idx_event_timestamp', table_name='central_memory_bank')
    op.drop_index('idx_cross_agent', table_name='central_memory_bank')
    op.drop_index('idx_agent_user', table_name='central_memory_bank')
    op.drop_index('idx_agent_memories', table_name='central_memory_bank')
    op.drop_table('central_memory_bank')
    op.drop_index('ix_mem_user_agent_type_time', table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_user_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_timestamp'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_memory_type'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_agent_name'), table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_index(op.f('ix_agent_learning_interactions_timestamp'), table_name='agent_learning_interactions')
    op.drop_index(op.f('ix_agent_learning_interactions_target_agent'), table_name='agent_learning_interactions')
    op.drop_index(op.f('ix_agent_learning_interactions_source_agent'), table_name='agent_learning_interactions')
    op.drop_index('idx_learning_transfer', table_name='agent_learning_interactions')
    op.drop_index('idx_learning_effectiveness', table_name='agent_learning_interactions')
    op.drop_table('agent_learning_interactions')
    op.drop_index(op.f('ix_agent_global_patterns_pattern_key'), table_name='agent_global_patterns')
    op.drop_table('agent_global_patterns')
    # ### end Alembic commands ###
