"""add central_memory_id_to_action_outcomes

Revision ID: c0ecfec9e5af
Revises: 58e893ae4e16
Create Date: 2026-02-18 10:06:29.021308
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0ecfec9e5af'
down_revision: Union[str, None] = '58e893ae4e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_event_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('agent_state', sa.String(length=50), nullable=True),
    sa.Column('date_partition', sa.Date(), nullable=False),
    sa.Column('ttl_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_event_log'))
    )
    op.create_index('idx_agent_event_time', 'agent_event_log', ['agent_name', 'event_type', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_date_partition', 'agent_event_log', ['date_partition'], unique=False, postgresql_using='btree')
    op.create_index('idx_event_data_gin', 'agent_event_log', ['event_data'], unique=False, postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.create_index('idx_event_type_time', 'agent_event_log', ['event_type', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_severity_time', 'agent_event_log', ['severity', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_ttl_cleanup', 'agent_event_log', ['ttl_expires_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_user_event_time', 'agent_event_log', ['user_id', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_agent_event_log_agent_name'), 'agent_event_log', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_event_log_date_partition'), 'agent_event_log', ['date_partition'], unique=False)
    op.create_index(op.f('ix_agent_event_log_event_type'), 'agent_event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_event_log_severity'), 'agent_event_log', ['severity'], unique=False)
    op.create_index(op.f('ix_agent_event_log_timestamp'), 'agent_event_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_event_log_ttl_expires_at'), 'agent_event_log', ['ttl_expires_at'], unique=False)
    op.create_index(op.f('ix_agent_event_log_user_id'), 'agent_event_log', ['user_id'], unique=False)
    op.create_table('agent_significant_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('significance_reason', sa.String(length=255), nullable=False),
    sa.Column('learned_pattern_id', sa.String(length=36), nullable=True),
    sa.Column('contributed_to_learning', sa.Boolean(), nullable=True),
    sa.Column('never_forget', sa.Boolean(), nullable=True),
    sa.Column('times_referenced', sa.Integer(), nullable=True),
    sa.Column('last_referenced', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_significant_events'))
    )
    op.create_index('idx_most_referenced', 'agent_significant_events', ['times_referenced', 'agent_name'], unique=False, postgresql_using='btree')
    op.create_index('idx_never_forget', 'agent_significant_events', ['never_forget', 'agent_name'], unique=False, postgresql_using='btree')
    op.create_index('idx_significant_agent_type', 'agent_significant_events', ['agent_name', 'event_type', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_significant_data_gin', 'agent_significant_events', ['event_data'], unique=False, postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.create_index('idx_user_significant', 'agent_significant_events', ['user_id', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_agent_significant_events_agent_name'), 'agent_significant_events', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_significant_events_event_type'), 'agent_significant_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_significant_events_never_forget'), 'agent_significant_events', ['never_forget'], unique=False)
    op.create_index(op.f('ix_agent_significant_events_timestamp'), 'agent_significant_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_agent_significant_events_user_id'), 'agent_significant_events', ['user_id'], unique=False)
    op.create_table('agent_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('agent_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_statistics'))
    )
    op.create_index('idx_agent_period', 'agent_statistics', ['agent_name', 'period_type', 'period_start'], unique=False, postgresql_using='btree')
    op.create_index('idx_period_range', 'agent_statistics', ['period_type', 'period_start', 'period_end'], unique=False, postgresql_using='btree')
    op.create_index('idx_user_period', 'agent_statistics', ['user_id', 'period_type', 'period_start'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_agent_statistics_agent_name'), 'agent_statistics', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_statistics_period_start'), 'agent_statistics', ['period_start'], unique=False)
    op.create_index(op.f('ix_agent_statistics_user_id'), 'agent_statistics', ['user_id'], unique=False)
    op.drop_index(op.f('idx_agent_action'), table_name='agent_learning_records')
    op.drop_index(op.f('idx_agent_fingerprint_success'), table_name='agent_learning_records')
    op.drop_index(op.f('idx_created'), table_name='agent_learning_records')
    op.drop_index(op.f('idx_fingerprint_l1'), table_name='agent_learning_records')
    op.drop_index(op.f('idx_fingerprint_l2'), table_name='agent_learning_records')
    op.drop_index(op.f('idx_fingerprint_l3'), table_name='agent_learning_records')
    op.drop_index(op.f('idx_process_category'), table_name='agent_learning_records')
    op.drop_index(op.f('idx_success'), table_name='agent_learning_records')
    op.drop_table('agent_learning_records')
    op.add_column('action_outcome_records', sa.Column('central_memory_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_action_outcome_records_central_memory_id'), 'action_outcome_records', ['central_memory_id'], unique=False)
    op.alter_column('agent_decision_vectors', 'decision_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agent_decision_vectors', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=app.models.vector_tables.Vector(),
               existing_nullable=False)
    op.alter_column('agent_decision_vectors', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('agent_decision_vectors', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('agent_decision_vectors', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('agent_decision_vectors', 'decision_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('agent_decision_vectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('agent_decision_vectors_embedding_idx'), table_name='agent_decision_vectors', postgresql_ops={'(embedding::vector(384))': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_agent_decision_vectors_agent_time'), table_name='agent_decision_vectors')
    op.drop_index(op.f('idx_agent_decision_vectors_metadata'), table_name='agent_decision_vectors', postgresql_using='gin')
    op.drop_index(op.f('idx_agent_decision_vectors_type'), table_name='agent_decision_vectors')
    op.drop_index(op.f('idx_agent_decision_vectors_user'), table_name='agent_decision_vectors')
    op.drop_constraint(op.f('uq_agent_decision_vectors_vector_id'), 'agent_decision_vectors', type_='unique')
    op.create_index('idx_decision_agent_time', 'agent_decision_vectors', ['agent_name', 'occurred_at'], unique=False)
    op.create_index('idx_decision_user_time', 'agent_decision_vectors', ['user_id', 'occurred_at'], unique=False)
    op.create_index('idx_decision_vectors_hnsw', 'agent_decision_vectors', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_agent_decision_vectors_agent_name'), 'agent_decision_vectors', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_decision_vectors_decision_type'), 'agent_decision_vectors', ['decision_type'], unique=False)
    op.create_index(op.f('ix_agent_decision_vectors_occurred_at'), 'agent_decision_vectors', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_agent_decision_vectors_user_id'), 'agent_decision_vectors', ['user_id'], unique=False)
    op.drop_column('agent_decision_vectors', 'embedding_model')
    op.drop_column('agent_decision_vectors', 'id')
    op.alter_column('agent_interaction_vectors', 'secondary_agent',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('agent_interaction_vectors', 'interaction_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('agent_interaction_vectors', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=app.models.vector_tables.Vector(),
               existing_nullable=False)
    op.alter_column('agent_interaction_vectors', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('agent_interaction_vectors', 'interaction_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('agent_interaction_vectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('agent_interaction_vectors_embedding_idx'), table_name='agent_interaction_vectors', postgresql_ops={'(embedding::vector(384))': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_agent_interaction_vectors_pair'), table_name='agent_interaction_vectors')
    op.drop_index(op.f('idx_agent_interaction_vectors_primary'), table_name='agent_interaction_vectors')
    op.drop_index(op.f('idx_agent_interaction_vectors_secondary'), table_name='agent_interaction_vectors')
    op.drop_index(op.f('idx_agent_interaction_vectors_user'), table_name='agent_interaction_vectors')
    op.drop_constraint(op.f('uq_agent_interaction_vectors_vector_id'), 'agent_interaction_vectors', type_='unique')
    op.create_index('idx_interaction_agents_time', 'agent_interaction_vectors', ['primary_agent', 'secondary_agent', 'occurred_at'], unique=False)
    op.create_index('idx_interaction_user_time', 'agent_interaction_vectors', ['user_id', 'occurred_at'], unique=False)
    op.create_index('idx_interaction_vectors_hnsw', 'agent_interaction_vectors', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_agent_interaction_vectors_interaction_type'), 'agent_interaction_vectors', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_agent_interaction_vectors_occurred_at'), 'agent_interaction_vectors', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_agent_interaction_vectors_primary_agent'), 'agent_interaction_vectors', ['primary_agent'], unique=False)
    op.create_index(op.f('ix_agent_interaction_vectors_secondary_agent'), 'agent_interaction_vectors', ['secondary_agent'], unique=False)
    op.create_index(op.f('ix_agent_interaction_vectors_user_id'), 'agent_interaction_vectors', ['user_id'], unique=False)
    op.drop_column('agent_interaction_vectors', 'id')
    op.alter_column('agent_pattern_vectors', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=app.models.vector_tables.Vector(),
               existing_nullable=False)
    op.drop_index(op.f('agent_pattern_vectors_embedding_idx'), table_name='agent_pattern_vectors', postgresql_ops={'(embedding::vector(384))': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('agent_pattern_vectors_embedding_idx', 'agent_pattern_vectors', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('idx_agent_pattern_vectors_user'), table_name='agent_pattern_vectors')
    op.create_index('idx_agent_pattern_vectors_user', 'agent_pattern_vectors', ['user_id', 'last_observed'], unique=False)
    op.create_index(op.f('ix_agent_pattern_vectors_agent_name'), 'agent_pattern_vectors', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_pattern_vectors_last_observed'), 'agent_pattern_vectors', ['last_observed'], unique=False)
    op.create_index(op.f('ix_agent_pattern_vectors_pattern_type'), 'agent_pattern_vectors', ['pattern_type'], unique=False)
    op.drop_constraint(op.f('fk_hamsters_memory_bank_central_memory_id_central_memory_bank'), 'hamsters_memory_bank', type_='foreignkey')
    op.drop_constraint(op.f('fk_meth_snail_memory_bank_central_memory_id_central_memory_bank'), 'meth_snail_memory_bank', type_='foreignkey')
    op.drop_constraint(op.f('fk_the_stick_memory_bank_central_memory_id_central_memory_bank'), 'the_stick_memory_bank', type_='foreignkey')
    op.drop_constraint(op.f('fk_vic20_memory_bank_central_memory_id_central_memory_bank'), 'vic20_memory_bank', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_vic20_memory_bank_central_memory_id_central_memory_bank'), 'vic20_memory_bank', 'central_memory_bank', ['central_memory_id'], ['memory_id'])
    op.create_foreign_key(op.f('fk_the_stick_memory_bank_central_memory_id_central_memory_bank'), 'the_stick_memory_bank', 'central_memory_bank', ['central_memory_id'], ['memory_id'])
    op.create_foreign_key(op.f('fk_meth_snail_memory_bank_central_memory_id_central_memory_bank'), 'meth_snail_memory_bank', 'central_memory_bank', ['central_memory_id'], ['memory_id'])
    op.create_foreign_key(op.f('fk_hamsters_memory_bank_central_memory_id_central_memory_bank'), 'hamsters_memory_bank', 'central_memory_bank', ['central_memory_id'], ['memory_id'])
    op.drop_index(op.f('ix_agent_pattern_vectors_pattern_type'), table_name='agent_pattern_vectors')
    op.drop_index(op.f('ix_agent_pattern_vectors_last_observed'), table_name='agent_pattern_vectors')
    op.drop_index(op.f('ix_agent_pattern_vectors_agent_name'), table_name='agent_pattern_vectors')
    op.drop_index('idx_agent_pattern_vectors_user', table_name='agent_pattern_vectors')
    op.create_index(op.f('idx_agent_pattern_vectors_user'), 'agent_pattern_vectors', ['user_id', sa.literal_column('last_observed DESC')], unique=False)
    op.drop_index('agent_pattern_vectors_embedding_idx', table_name='agent_pattern_vectors', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('agent_pattern_vectors_embedding_idx'), 'agent_pattern_vectors', [sa.literal_column('(embedding::vector(384))')], unique=False, postgresql_ops={'(embedding::vector(384))': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('agent_pattern_vectors', 'embedding',
               existing_type=app.models.vector_tables.Vector(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    op.add_column('agent_interaction_vectors', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_agent_interaction_vectors_user_id'), table_name='agent_interaction_vectors')
    op.drop_index(op.f('ix_agent_interaction_vectors_secondary_agent'), table_name='agent_interaction_vectors')
    op.drop_index(op.f('ix_agent_interaction_vectors_primary_agent'), table_name='agent_interaction_vectors')
    op.drop_index(op.f('ix_agent_interaction_vectors_occurred_at'), table_name='agent_interaction_vectors')
    op.drop_index(op.f('ix_agent_interaction_vectors_interaction_type'), table_name='agent_interaction_vectors')
    op.drop_index('idx_interaction_vectors_hnsw', table_name='agent_interaction_vectors', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_interaction_user_time', table_name='agent_interaction_vectors')
    op.drop_index('idx_interaction_agents_time', table_name='agent_interaction_vectors')
    op.create_unique_constraint(op.f('uq_agent_interaction_vectors_vector_id'), 'agent_interaction_vectors', ['vector_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_agent_interaction_vectors_user'), 'agent_interaction_vectors', ['user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_interaction_vectors_secondary'), 'agent_interaction_vectors', ['secondary_agent', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_interaction_vectors_primary'), 'agent_interaction_vectors', ['primary_agent', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_interaction_vectors_pair'), 'agent_interaction_vectors', ['primary_agent', 'secondary_agent', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('agent_interaction_vectors_embedding_idx'), 'agent_interaction_vectors', [sa.literal_column('(embedding::vector(384))')], unique=False, postgresql_ops={'(embedding::vector(384))': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('agent_interaction_vectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_interaction_vectors', 'interaction_summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agent_interaction_vectors', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_interaction_vectors', 'embedding',
               existing_type=app.models.vector_tables.Vector(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    op.alter_column('agent_interaction_vectors', 'interaction_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agent_interaction_vectors', 'secondary_agent',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('agent_decision_vectors', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.add_column('agent_decision_vectors', sa.Column('embedding_model', sa.VARCHAR(length=100), server_default=sa.text("'all-MiniLM-L6-v2'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agent_decision_vectors_user_id'), table_name='agent_decision_vectors')
    op.drop_index(op.f('ix_agent_decision_vectors_occurred_at'), table_name='agent_decision_vectors')
    op.drop_index(op.f('ix_agent_decision_vectors_decision_type'), table_name='agent_decision_vectors')
    op.drop_index(op.f('ix_agent_decision_vectors_agent_name'), table_name='agent_decision_vectors')
    op.drop_index('idx_decision_vectors_hnsw', table_name='agent_decision_vectors', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_decision_user_time', table_name='agent_decision_vectors')
    op.drop_index('idx_decision_agent_time', table_name='agent_decision_vectors')
    op.create_unique_constraint(op.f('uq_agent_decision_vectors_vector_id'), 'agent_decision_vectors', ['vector_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_agent_decision_vectors_user'), 'agent_decision_vectors', ['user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_decision_vectors_type'), 'agent_decision_vectors', ['decision_type', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_agent_decision_vectors_metadata'), 'agent_decision_vectors', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_agent_decision_vectors_agent_time'), 'agent_decision_vectors', ['agent_name', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('agent_decision_vectors_embedding_idx'), 'agent_decision_vectors', [sa.literal_column('(embedding::vector(384))')], unique=False, postgresql_ops={'(embedding::vector(384))': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('agent_decision_vectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_decision_vectors', 'decision_summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agent_decision_vectors', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_decision_vectors', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('agent_decision_vectors', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('agent_decision_vectors', 'embedding',
               existing_type=app.models.vector_tables.Vector(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    op.alter_column('agent_decision_vectors', 'decision_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_action_outcome_records_central_memory_id'), table_name='action_outcome_records')
    op.drop_column('action_outcome_records', 'central_memory_id')
    op.create_table('agent_learning_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fingerprint_l1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fingerprint_l2', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fingerprint_l3', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('root_cause', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('process_category', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('followed_vic20', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('improvement', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('what_worked', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('what_failed', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_learning_records'))
    )
    op.create_index(op.f('idx_success'), 'agent_learning_records', ['success'], unique=False)
    op.create_index(op.f('idx_process_category'), 'agent_learning_records', ['process_category'], unique=False)
    op.create_index(op.f('idx_fingerprint_l3'), 'agent_learning_records', ['fingerprint_l3'], unique=False)
    op.create_index(op.f('idx_fingerprint_l2'), 'agent_learning_records', ['fingerprint_l2'], unique=False)
    op.create_index(op.f('idx_fingerprint_l1'), 'agent_learning_records', ['fingerprint_l1'], unique=False)
    op.create_index(op.f('idx_created'), 'agent_learning_records', ['created_at'], unique=False)
    op.create_index(op.f('idx_agent_fingerprint_success'), 'agent_learning_records', ['agent_name', 'fingerprint_l3', 'success'], unique=False)
    op.create_index(op.f('idx_agent_action'), 'agent_learning_records', ['agent_name', 'action'], unique=False)
    op.drop_index(op.f('ix_agent_statistics_user_id'), table_name='agent_statistics')
    op.drop_index(op.f('ix_agent_statistics_period_start'), table_name='agent_statistics')
    op.drop_index(op.f('ix_agent_statistics_agent_name'), table_name='agent_statistics')
    op.drop_index('idx_user_period', table_name='agent_statistics', postgresql_using='btree')
    op.drop_index('idx_period_range', table_name='agent_statistics', postgresql_using='btree')
    op.drop_index('idx_agent_period', table_name='agent_statistics', postgresql_using='btree')
    op.drop_table('agent_statistics')
    op.drop_index(op.f('ix_agent_significant_events_user_id'), table_name='agent_significant_events')
    op.drop_index(op.f('ix_agent_significant_events_timestamp'), table_name='agent_significant_events')
    op.drop_index(op.f('ix_agent_significant_events_never_forget'), table_name='agent_significant_events')
    op.drop_index(op.f('ix_agent_significant_events_event_type'), table_name='agent_significant_events')
    op.drop_index(op.f('ix_agent_significant_events_agent_name'), table_name='agent_significant_events')
    op.drop_index('idx_user_significant', table_name='agent_significant_events', postgresql_using='btree')
    op.drop_index('idx_significant_data_gin', table_name='agent_significant_events', postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.drop_index('idx_significant_agent_type', table_name='agent_significant_events', postgresql_using='btree')
    op.drop_index('idx_never_forget', table_name='agent_significant_events', postgresql_using='btree')
    op.drop_index('idx_most_referenced', table_name='agent_significant_events', postgresql_using='btree')
    op.drop_table('agent_significant_events')
    op.drop_index(op.f('ix_agent_event_log_user_id'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_ttl_expires_at'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_timestamp'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_severity'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_event_type'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_date_partition'), table_name='agent_event_log')
    op.drop_index(op.f('ix_agent_event_log_agent_name'), table_name='agent_event_log')
    op.drop_index('idx_user_event_time', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_ttl_cleanup', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_severity_time', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_event_type_time', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_event_data_gin', table_name='agent_event_log', postgresql_using='gin', postgresql_ops={'event_data': 'jsonb_path_ops'})
    op.drop_index('idx_date_partition', table_name='agent_event_log', postgresql_using='btree')
    op.drop_index('idx_agent_event_time', table_name='agent_event_log', postgresql_using='btree')
    op.drop_table('agent_event_log')
    # ### end Alembic commands ###
