"""Add embedding_model to agent_decision_vectors

Revision ID: 2e71b1b4ca75
Revises: c0ecfec9e5af
Create Date: 2026-03-04 12:25:31.353756
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e71b1b4ca75'
down_revision: Union[str, None] = 'c0ecfec9e5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learning_event_log_created_at', table_name='learning_event_log')
    op.drop_index('ix_learning_event_log_event_id', table_name='learning_event_log')
    op.drop_index('ix_learning_event_log_event_type', table_name='learning_event_log')
    op.drop_index('ix_learning_event_log_id', table_name='learning_event_log')
    op.drop_index('ix_learning_event_log_source_agent', table_name='learning_event_log')
    op.drop_index('ix_learning_event_log_source_envelope_id', table_name='learning_event_log')
    op.drop_index('ix_learning_event_log_source_learning_record_id', table_name='learning_event_log')
    op.drop_index('ix_learning_event_log_target_agent', table_name='learning_event_log')
    op.drop_table('learning_event_log')
    op.drop_index('ix_decision_envelopes_action', table_name='decision_envelopes')
    op.drop_index('ix_decision_envelopes_agent_name', table_name='decision_envelopes')
    op.drop_index('ix_decision_envelopes_created_at', table_name='decision_envelopes')
    op.drop_index('ix_decision_envelopes_envelope_id', table_name='decision_envelopes')
    op.drop_index('ix_decision_envelopes_environment', table_name='decision_envelopes')
    op.drop_index('ix_decision_envelopes_id', table_name='decision_envelopes')
    op.drop_index('ix_decision_envelopes_intent_class', table_name='decision_envelopes')
    op.drop_table('decision_envelopes')
    op.add_column('agent_decision_vectors', sa.Column('embedding_model', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_decision_vectors', 'embedding_model')
    op.create_table('decision_envelopes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('envelope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('intent_class', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('perception_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('reasoning', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('alternatives_considered', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('affected_resources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('estimated_impact', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('reversibility', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('backups_exist', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('backups_restorable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('rollback_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dry_run_executed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dry_run_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('predicted_outcome', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pre_state_fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('required_invariants', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('state_validated_at_execution', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('state_drift_detected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('state_drift_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approval_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('approval_granted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('approval_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_acknowledged_risks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('forced_delay_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('execution_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('execution_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('actual_impact', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('learning_record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('prev_envelope_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('environment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('operator_present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('execution_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('policy_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_decision_envelopes')
    )
    op.create_index('ix_decision_envelopes_intent_class', 'decision_envelopes', ['intent_class'], unique=False)
    op.create_index('ix_decision_envelopes_id', 'decision_envelopes', ['id'], unique=False)
    op.create_index('ix_decision_envelopes_environment', 'decision_envelopes', ['environment'], unique=False)
    op.create_index('ix_decision_envelopes_envelope_id', 'decision_envelopes', ['envelope_id'], unique=False)
    op.create_index('ix_decision_envelopes_created_at', 'decision_envelopes', ['created_at'], unique=False)
    op.create_index('ix_decision_envelopes_agent_name', 'decision_envelopes', ['agent_name'], unique=False)
    op.create_index('ix_decision_envelopes_action', 'decision_envelopes', ['action'], unique=False)
    op.create_table('learning_event_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_learning_record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_envelope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('target_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('propagation_chain', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('improvement', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('observability_quality', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('novelty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('operator_present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('execution_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('promotion_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('prev_event_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_learning_event_log')
    )
    op.create_index('ix_learning_event_log_target_agent', 'learning_event_log', ['target_agent'], unique=False)
    op.create_index('ix_learning_event_log_source_learning_record_id', 'learning_event_log', ['source_learning_record_id'], unique=False)
    op.create_index('ix_learning_event_log_source_envelope_id', 'learning_event_log', ['source_envelope_id'], unique=False)
    op.create_index('ix_learning_event_log_source_agent', 'learning_event_log', ['source_agent'], unique=False)
    op.create_index('ix_learning_event_log_id', 'learning_event_log', ['id'], unique=False)
    op.create_index('ix_learning_event_log_event_type', 'learning_event_log', ['event_type'], unique=False)
    op.create_index('ix_learning_event_log_event_id', 'learning_event_log', ['event_id'], unique=False)
    op.create_index('ix_learning_event_log_created_at', 'learning_event_log', ['created_at'], unique=False)
    # ### end Alembic commands ###
