"""
This type stub file was generated by pyright.
"""

class _AsyncGeneratorContextManager:
    """Helper for @asynccontextmanager."""
    def __init__(self, func, args, kwds) -> None:
        ...
    
    async def __aenter__(self):
        ...
    
    async def __aexit__(self, typ, value, traceback): # -> bool | None:
        ...
    


def asynccontextmanager(func): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], _AsyncGeneratorContextManager]:
    ...

