# Generated by Django 4.2.20 on 2025-03-16 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("NETWORK", "Network"),
                            ("SYSTEM", "System"),
                            ("SECURITY", "Security"),
                            ("PERFORMANCE", "Performance"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sir Hawkington's Configuration",
                "verbose_name_plural": "Sir Hawkington's Distinguished Configurations",
                "db_table": "system_configurations",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="system_conf_user_id_38a814_idx",
                    ),
                    models.Index(
                        fields=["config_type"], name="system_conf_config__05a260_idx"
                    ),
                ],
            },
        ),
    ]
